version: "3.5"

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    container_name: bookworm-database-server
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  server:
    env_file:
      - path: ./admin/.env
        required: true
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: bookworm-admin-server
    environment:
      - PORT=${PORT}
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - database

  # customer:
  #   build:
  #     context: ./customer
  #     dockerfile: Dockerfile
  #   container_name: bookworm-customer-client
  #   environment:
  #     - PORT=${PORT}
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - server

networks:
  my_network:
    driver: bridge
